#version: '3.8'
services: 
  # db:
  #   image: postgres:15
  #   restart: always
  #   ports:
  #     - "${DB_PORT}:${DB_PORT}"
      
  #   environment:
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_DB: ${DB_NAME}
  #   container_name: anylistDB
  #   volumes:
  #     - ./postgres:/var/lib/postgresql/data

  anylistapp:
  #Depende de que primero se construlla la imagen db
    # depends_on:
    #   - db
    build:
    #En la raiz va a buscar el archivo Dockerfile que es donde estan las instrucciones para construir la imagen de la aplicacion
      context: .
      dockerfile: Dockerfile
      args:
        - ARG_DATABASE_URL=${DATABASE_URL}
        #- ARG_DB_HOST=${DB_HOST}


    #image: nest-graphql
    #Va a buscar la imgen e duckerhub
    image: jotacollantes/nest-graphql-prod:1.0.0
    container_name: AnylistApp
    #restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"

    environment:
      STATE: ${STATE}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}